# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
image: docker
services:
  - docker:dind
variables:  
  DOCKER_HOST: tcp://localhost:2375/
  imageTag: latest
  env: prod

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always  
    - if: $CI_COMMIT_BRANCH == 'develop'
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH != 'develop'
      when: never

before_script:
  - echo "Before script section"
  - while ! nc -z localhost 2375 ; do sleep 1 ; done
  - docker login -u $ACR_USER -p $ACR_KEY hssdevacr.azurecr.io
  - docker info
  - echo $imageTag

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

docker-build-idp:
  stage: build
  script:    
    - cd backend

    - docker build -t hss-idp-api:$imageTag -f HSS.IdentityServer/Dockerfile . 

    - docker image tag hss-idp-api:$imageTag hssdevacr.azurecr.io/hss-idp-api:$imageTag
    - docker image push hssdevacr.azurecr.io/hss-idp-api:$imageTag

docker-build-hub:
  stage: build
  script:    
    - cd backend

    - docker build -t hss-hub-api:$imageTag -f HSS.HubServer/Dockerfile . 

    - docker image tag hss-hub-api:$imageTag hssdevacr.azurecr.io/hss-hub-api:$imageTag
    - docker image push hssdevacr.azurecr.io/hss-hub-api:$imageTag

docker-build-user:
  stage: build
  script:    
    - cd backend

    - docker build -t hss-user-api:$imageTag -f HSS.UserApi/Dockerfile .
    - docker build -t hss-message-api:$imageTag -f HSS.MessageApi/Dockerfile .
    - docker build -t hss-signalrdemo-api:$imageTag -f HSS.SignalRDemo/Dockerfile .

    - docker image tag hss-user-api:$imageTag hssdevacr.azurecr.io/hss-user-api:$imageTag
    - docker image push hssdevacr.azurecr.io/hss-user-api:$imageTag

    - docker image tag hss-message-api:$imageTag hssdevacr.azurecr.io/hss-message-api:$imageTag
    - docker image push hssdevacr.azurecr.io/hss-message-api:$imageTag

    - docker image tag hss-signalrdemo-api:$imageTag hssdevacr.azurecr.io/hss-signalrdemo-api:$imageTag
    - docker image push hssdevacr.azurecr.io/hss-signalrdemo-api:$imageTag

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

deploy-infrastructure:
  stage: deploy
  before_script:
    - ''
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - echo "Deploy infrastructure"
    - cd devops/aks/terraform/profiles/prod
    - rm -rf .terraform
    - terraform --version
    - terraform init
    - terraform apply -auto-approve

deploy-services:
  stage: deploy
  before_script:
    - apk add py3-pip
    - apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo make
    - pip install --upgrade pip
    - pip install azure-cli
    - sh
    - az login --service-principal --username="${ARM_CLIENT_ID}" --password="${ARM_CLIENT_SECRET}" --tenant=${ARM_TENANT_ID}
  image: dtzar/helm-kubectl:latest
  needs: ['deploy-infrastructure']
  script:
    - echo "Deploy services"
    - cd devops/aks/services
    - sh basic_services.sh $env
    - sh hss_services.sh $env $imageTag
