package auth

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/web-service-dlw/user-api/auth/jwt"
	"github.com/web-service-dlw/user-api/aws"
	"github.com/web-service-dlw/user-api/users/entity"
	"github.com/web-service-dlw/user-api/users/repository"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/github"
)

const githubUserUrl = "https://api.github.com/user"

type GitHubUser struct {
	Email     string `json:"email"`
	Login     string `json:"login"`
	Id        int    `json:"id"`
	AvatarUrl string `json:"avatar_url"`
}

var confGitHub *oauth2.Config

var repo *repository.UserRepo

func init() {
	repo = &repository.UserRepo{
		TableName: "dlf.Users",
		DynamoDB:  aws.GetDynamoDBClient(),
	}
}

func init() {
	confGitHub = &oauth2.Config{
		ClientID:     aws.Parameters["/dlf/dev/githubClientId"],
		ClientSecret: aws.Parameters["/dlf/dev/githubClientSecret"],
		Scopes:       []string{"read:user", "user:email", "read:repo_hook"},
		Endpoint:     github.Endpoint,
	}
}

/**
* generate github authorize url and redirect directly
**/
func AuthorizeGithub(c *gin.Context) {
	//ctx := context.Background()
	//generate state and return to client can stop CSRF
	url := confGitHub.AuthCodeURL("state123", oauth2.AccessTypeOffline)

	c.Redirect(http.StatusTemporaryRedirect, url)
}

/**
* generate github authorize url and return url
**/
func AuthorizeGithubUrl(c *gin.Context) {
	//ctx := context.Background()
	//generate state and return to client can stop CSRF
	url := confGitHub.AuthCodeURL("state123", oauth2.AccessTypeOffline)

	c.String(http.StatusOK, url)
}

/**
GetTokenGithub
* Call github api again in backend (for security reason),
* 1. get access token generated by github
* 2. get github user
* 3. check native user by email
* 3.1.0 update native user  -- email exists
* 3.2.0 add native user     -- email not exists
* 4 generate jwt token
* 5 return token
**/
func GetTokenGithub(c *gin.Context) {
	code := c.Query("code")
	state := c.Query("state")

	if code == "" {
		c.JSON(http.StatusUnauthorized, "Token not found.")
	}

	if state != "state123" {
		c.JSON(http.StatusBadGateway, "Invalid state.")
	}

	//TODO: how to verify dynamic csrf token
	token, err := confGitHub.Exchange(c.Request.Context(), code)
	if err != nil {
		log.Fatal(err.Error())
		c.String(http.StatusBadRequest, err.Error())
	}

	c.JSON(http.StatusOK, token)
}

/*
GetUserGitHub - Get github user info and register in to our database
*/
func GetUserGitHub(c *gin.Context) {
	token := c.Query("access_token")
	url := "https://api.github.com/user"

	user, err := getGithubUser(url, token)
	if err != nil {
		log.Fatal(err.Error())
		c.String(http.StatusInternalServerError, err.Error())
	}

	nativeUser, err := repo.GetUserByEmail(user.Email)
	if err != nil {
		repo.CreateUser(&entity.User{
			AvatarUrl: user.AvatarUrl,
			Email:     user.Email,
			Name:      user.Login,
			Birthday:  "2000-01-01",
			Address:   make([]entity.Address, 0),
		})

		nativeUser, err = repo.GetUserByEmail(user.Email)
	}

	if err != nil {
		c.String(http.StatusInternalServerError, err.Error())
	}

	nativeToken, err := jwt.NewToken(nativeUser.Id, nativeUser.Email)
	if err != nil {
		c.String(http.StatusInternalServerError, err.Error())
	}

	c.JSON(http.StatusOK, nativeToken)
}

/*
GetUserGitHub - Get github user info and register in to our database
*/
func TempCheckToken(c *gin.Context) {
	token := c.Query("access_code")
	if token == "" {
		token = c.GetHeader("Authorization")
		token = token[7:]
	}

	claims, err := jwt.ParseToken(token)
	if err != nil {
		c.String(http.StatusInternalServerError, err.Error())
	}

	c.JSON(http.StatusOK, claims)
}

func getGithubUser(url, token string) (*GitHubUser, error) {
	request, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		log.Fatal(err.Error())
		return nil, err
	}

	request.Header.Add("Authorization", fmt.Sprintf("token %v", token))
	response, err := http.DefaultClient.Do(request)

	if err != nil {
		log.Fatal(err.Error())
		return nil, err
	}

	responseData, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}

	var user *GitHubUser = &GitHubUser{}
	json.Unmarshal(responseData, &user)

	return user, nil
}
