serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = 7000
includes = ["./config/*.toml"]

transport.poolCount = 1

#transport.tls.enable = true
#transport.tls.certFile = "server.crt"
#transport.tls.keyFile = "server.key"
#transport.tls.trustedCaFile = "ca.crt"