AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  bucketName:
    Type: String
    Default: ken-photo-board-test
  tableName:
    Type: String
    Default: photos
  roleName:
    Type: String
    Default: lambda_role_s3_dynamo_full_access
  functionName:
    Type: String
    Default: photo-process-lambda
Resources:
  role:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Allows Lambda functions to call AWS services on your behalf. 
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      RoleName: !Ref roleName
  dynamodb:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "s3bucket"
          AttributeType: "S"
        - 
          AttributeName: "s3key"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "s3bucket"
          KeyType: "HASH"
        - 
          AttributeName: "s3key"
          KeyType: "RANGE"
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
      TableName: !Ref tableName
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/s3-to-dynamodb-1.0-SNAPSHOT.jar
      Handler: S3ToDynamoDB.Handler::handleRequest
      Runtime: java11
      FunctionName: !Ref functionName
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Role: !GetAtt role.Arn
      #Policies:
      #  - AWSLambdaBasicExecutionRole
      #  - AWSLambda_ReadOnlyAccess
      #  - AWSXrayWriteOnlyAccess
      #  - AWSLambdaVPCAccessExecutionRole
      #  - AmazonS3FullAccess
      Tracing: Active
      Events:
        s3Notification:
          Type: S3
          Properties:
            Bucket: !Ref bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: original/
