import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import {GetProblems} from '../../../api/request'
import {MathCategory, MathKind, MathType} from '../const'

const initialState = { 
    Criterias: [],
    Questions: [],
    ShowResult: false
};
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const loadAsync = createAsyncThunk(
    'criteria/GetProblems',
    async (criterias) => {
      const response = await GetProblems(criterias);
      // The value we return becomes the `fulfilled` action payload
      return response.data;
    }
  );

export const criteriaSlice = createSlice({
    name: 'criteria',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        saveCriterias(state, action) {
            state.Criterias.push(action.payload)
        },

        clearAll(state) {
            state.Criterias = []
            state.Questions = []
            state.CheckResult = false
            state.ShowAnswer = false
            state.Score = 0
        },

        checkResult(state) {
            state.CheckResult = !state.CheckResult
        },

        showAnswer(state) {
          state.ShowAnswer = !state.ShowAnswer
        },

        submitResult(state) {
          const correct = state.Questions.filter(x=>x.Answer === x.UserAnswer).length
          const score = correct / state.Questions.length * 100
          state.Score = score
        },

        updateAnswer(state, action) {
          const {index, answer} = action.payload
          state.Questions.at(index).UserAnswer = answer
         },
         addCriteriaTemplate(state, action){
          const {category, quantity, max} = action.payload

          var criterias = []
          MathCategory.forEach(cat => {
            if(category!=-1 && category!= cat.value){
              return
            }
            MathKind.forEach(kind => {
              MathType.forEach(type =>{
                const criteria = {
                  Min: 0, Max: max,
                  Quantity: quantity,
              
                  Range:{
                      Min: 0,
                      Max:max,
                  },
              
                  Category: cat.value, 
                  Kind: kind.value, 
                  Type: type.value
              }

              criterias.push(criteria)
              })
            })

          });

          state.Criterias = criterias
         }
    },  
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(loadAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(loadAsync.fulfilled, (state, action) => {
          state.status = 'idle';
          state.Questions = action.payload;
        });
    },
});

export const { clearAll, saveCriterias, checkResult, showAnswer, submitResult,updateAnswer,addCriteriaTemplate} = criteriaSlice.actions;
export const currentCriterias = (state) => state.criteria.Criterias;
export const currentQuestions = (state) => state.criteria.Questions;
export const currentCheckResult = (state) => state.criteria.CheckResult;
export const currentShowAnswer = (state) => state.criteria.ShowAnswer;
export const currentScore = (state) => state.criteria.Score;

export default criteriaSlice.reducer;