import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import {GetProblems} from '../../../api/request'

const initialState = { 
    Criterias: [],
    Questions: []
};
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const loadAsync = createAsyncThunk(
    'criteria/GetProblems',
    async (data, {getState }) => {
      const state = getState();
      const response = await GetProblems(state.criteria.Criterias);
      // The value we return becomes the `fulfilled` action payload
      return response.data;
    }
  );

export const criteriaSlice = createSlice({
    name: 'criteria',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        saveCriterias(state, action) {
            state.Criterias.push(action.payload)
        },

        clearAll(state) {
            state.Criterias = []
            state.Questions = []
        },

        loadDate(state, action) {
            state.Questions =action.payload
        },
    },  
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(loadAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(loadAsync.fulfilled, (state, action) => {
          state.status = 'idle';
          state.Questions = action.payload;
        });
    },
});

export const { clearAll, saveCriterias, loadDate} = criteriaSlice.actions;
export const currentCriterias = (state) => state.criteria.Criterias;
export const currentQuestions = (state) => state.criteria.Questions;

export default criteriaSlice.reducer;