import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { SearchMemo } from '../../api/request';

// Distrct/Street/Community/MinPrice/MaxPrice/Version/SortKey/Page/Size
const initialState = {
  Criteria: {
    StartDate: '2022-01-01',
    EndDate: '2022-12-31',
  },
  MemoItems: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const loadAsync = createAsyncThunk(
  'memo/Search',
  async (criteria) => {
    const response = await SearchMemo(criteria);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  },
);

export const memoSlice = createSlice({
  name: 'memo',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    saveCriteria(state, action) {
      state.MemoItems = [];
      state.Criteria = action.payload;
    },
    loadMore(state) {
      state.status = 'ready';
      state.Criteria.Page += 1;
    },
    clearAll(state) {
      if (JSON.stringify(state.Criteria) === JSON.stringify(initialState.Criteria)) {
        return;
      }
      state.Criteria = initialState.Criteria;
      state.MemoItems = [];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loadAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(loadAsync.fulfilled, (state, action) => {
        const items = action.payload;
        state.status = 'idle';
        const results = state.MemoItems;
        items.forEach((item) => {
          if (!results.some((r) => r.Id === item.Id)) {
            results.push(item);
          }
        });
        state.MemoItems = results;
      });
  },
});

export const { saveCriteria, clearAll, loadMore } = memoSlice.actions;
export const currentCriteria = (state) => state.memo.Criteria;
export const currentItems = (state) => state.memo.MemoItems;
export const loadingStatus = (state) => state.memo.status;

export default memoSlice.reducer;
