trigger:
  branches:
    include:
    - develop
  paths:
    include:
      - src/
      - azure-pipelines.yml
parameters:
  - name: environment
    displayName: Where to deploy?
    type: string
    default: dev
    values:
    - prod
    - dev
  - name: imageTag
    displayName: Docker image tag
    type: string
    default: latest
    
variables:
- group: ${{parameters.environment}}-variable-group
- name: env
  value: ${{parameters.environment}}
- name: imageTag
  value: ${{parameters.imageTag}}

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  
jobs:
  ## need include tests step
- job: runTests
  displayName: Run Tests # Human-readable name for the job. 
  timeoutInMinutes: 5

  steps:
  - task: Bash@3
    displayName: 'Run Unit Tests'
    inputs:
      targetType: 'inline'
      script: |
        dotnet test
      workingDirectory: 'src/backend'
  #Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases

- job: buildAndPush
  displayName: Build and Push Images # Human-readable name for the job. 
  dependsOn: runTests
  timeoutInMinutes: 10

  steps:
  - task: Docker@2
    displayName: 'Build IDP image'
    inputs:
      containerRegistry: sharedacr
      repository: 'kse-idp-api'
      Dockerfile: 'src/backend/EStore.IdentityServer/Dockerfile'
      buildContext: 'src/backend'
      tags: '$(imageTag)'

  - task: Docker@2
    displayName: 'Build Cart image'
    inputs:
      containerRegistry: sharedacr
      repository: 'kse-cart-api'
      Dockerfile: 'src/backend/EStore.CartAPI/Dockerfile'
      buildContext: 'src/backend'
      tags: '$(imageTag)'

  - task: Docker@2
    displayName: 'Build Order image'
    inputs:
      containerRegistry: sharedacr
      repository: 'kse-order-api'
      Dockerfile: 'src/backend/EStore.OrderAPI/Dockerfile'
      buildContext: 'src/backend'
      tags: '$(imageTag)'

  - task: Docker@2
    displayName: 'Build User image'
    inputs:
      containerRegistry: sharedacr
      repository: 'kse-user-api'
      Dockerfile: 'src/backend/EStore.UserAPI/Dockerfile'
      buildContext: 'src/backend'
      tags: '$(imageTag)'

  - task: Docker@2
    displayName: 'Build Product image'
    inputs:
      containerRegistry: sharedacr
      repository: 'kse-product-api'
      Dockerfile: 'src/backend/EStore.ProductAPI/Dockerfile'
      buildContext: 'src/backend'
      tags: '$(imageTag)'

- job: provisioningInfrastructure
  displayName: Apply infrastructure # Human-readable name for the job. 
  dependsOn: buildAndPush
  timeoutInMinutes: 30

  steps:
  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
    displayName: 'Use Terraform latest'

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: 'terraform initial'
    inputs:
      command: init
      workingDirectory: 'devops/aks/terraform/profiles/$(env)'
      backendType: azurerm
      backendServiceArm: 'azure connection'
      backendAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      backendAzureRmResourceGroupName: 'configuration-rg'
      backendAzureRmStorageAccountName: configstoragefelix
      backendAzureRmContainerName: tfstate
      backendAzureRmKey: 'kse-$(env).nginx.tfstate'

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: 'terraform plan'
    inputs:
      command: plan
      workingDirectory: 'devops/aks/terraform/profiles/$(env)'
      environmentServiceName: 'azure connection'
      providerAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      runAzLogin: true
      backendServiceArm: 'azure connection'
      backendAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      backendAzureRmResourceGroupName: 'configuration-rg'
      backendAzureRmStorageAccountName: configstoragefelix
      backendAzureRmContainerName: tfstate
      backendAzureRmKey: 'kse-$(env).nginx.tfstate'
      publishPlanResults: 'kse-$(env)-plan'
      providerServiceAws: 'aws connection'
      providerAwsRegion: '$(AWS_DEFAULT_REGION)'

  - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
    displayName: 'terraform apply'
    inputs:
      command: apply
      workingDirectory: 'devops/aks/terraform/profiles/$(env)'
      environmentServiceName: 'azure connection'
      providerAzureRmSubscriptionId: '$(ARM_SUBSCRIPTION_ID)'
      runAzLogin: true
      commandOptions: '-auto-approve'
      providerServiceAws: 'aws connection'
      providerAwsRegion: '$(AWS_DEFAULT_REGION)'

- job: deployServices
  displayName: Deploy All Services # Human-readable name for the job. 
  dependsOn: provisioningInfrastructure
  timeoutInMinutes: 15

  steps:
  - task: AzureCLI@2
    displayName: 'Replace Keys & Tags'
    inputs:
      azureSubscription: 'azure connection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az login --service-principal --username="${ARM_CLIENT_ID}" --password="${ARM_CLIENT_SECRET}" --tenant=${ARM_TENANT_ID}
        sed -i "s/awsKeyIdPlaceHolder/$(echo -n $(AWS_ACCESS_KEY_ID) | base64)/" ./$(app)-chart/values_aks_$(env).yaml
        sed -i "s/awsSecretKeyPlaceHolder/$(echo -n $(AWS_SECRET_ACCESS_KEY) | base64)/" ./$(app)-chart/values_aks_$(env).yaml
        sed -i "s/imageVersion/$(imageTag)/" ./$(app)-chart/values_aks_$(env).yaml
        sed -i "s/connPlaceHolder/$(echo -n $(AppConnectionString) | base64 -w 0)/" ./$(app)-chart/values_aks_$(env).yaml
      workingDirectory: 'devops'

  - task: AzureCLI@2
    displayName: 'Deploy Basic Charts'
    inputs:
      azureSubscription: 'azure connection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        sh basic_services.sh $(env) $(app)
      useGlobalConfig: true
      workingDirectory: 'devops/aks/services'
      
  - task: AzureCLI@2
    displayName: 'Deploy Main Charts'
    inputs:
      azureSubscription: 'azure connection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        sh main_services.sh $(env) $(app)
      useGlobalConfig: true
      workingDirectory: 'devops/aks/services'

