---
- hosts: localhost
  vars:
     helm_chart_url: "https://charts.bitnami.com/bitnami"
  tasks:
      - name: Add helm repo
        kubernetes.core.helm_repository:
          name: bitnami
          repo_url: "{{ helm_chart_url }}"

      - name: Install Nginx Chart
        kubernetes.core.helm:
          name: nginx-server
          namespace: testing
          chart_ref: bitnami/nginx

      - name: Gather information about nginx-server
        kubernetes.core.helm_info:
          name: nginx-server
          release_namespace: testing

      - name: Install Helm Plugin
        kubernetes.core.helm_plugin:
          plugin_path: https://github.com/adamreese/helm-env
          state: present
          release_namespace: testing

      - name: Gather Helm plugin info
        kubernetes.core.helm_plugin_info:
          release_namespace: testing
        register: r

      - name: Print plugin version
        debug:
        msg: "{{ ( r.plugin_list | selectattr('name', 'equalto', plugin_name) | list )[0].version }}"
        vars:
        plugin_name: "env"